DROP DATABASE IF EXISTS repasTRIGGER;
CREATE DATABASE repasTRIGGER;
USE repasTRIGGER;

CREATE TABLE ALUMNE
	(CODI	INT AUTO_INCREMENT		PRIMARY KEY,
	NOM		VARCHAR(20),
    COGNOM	VARCHAR(20)
	)ENGINE = InnoDB
	;
CREATE TABLE LOGIN
	(CODI	INT AUTO_INCREMENT		PRIMARY KEY,
    NOM	VARCHAR(20)
	)ENGINE = InnoDB
	;
    
DELIMITER //
	CREATE TRIGGER REPAS_TRIGGER AFTER INSERT ON ALUMNE FOR EACH ROW
	BEGIN 
		INSERT INTO LOGIN VALUES (NEW.CODI,CONCAT(LOWER(LEFT(NEW.NOM,2)), LOWER(LEFT(NEW.COGNOM,2)),'@'));
	END // 
DELIMITER ; 

INSERT INTO ALUMNE (NOM, COGNOM) VALUES ('Alex', 'García');
INSERT INTO ALUMNE (NOM, COGNOM) VALUES ('Alberto', 'Gomez');
SELECT * FROM LOGIN;