DROP DATABASE IF EXISTS triggerBEFORE;
CREATE DATABASE triggerBEFORE;
USE triggerBEFORE;

CREATE TABLE USUARI
	(ID		INT(2)		PRIMARY KEY,
	NOM		VARCHAR(20),
    DATA_NAIX	DATE
	)ENGINE = InnoDB
	;

DELIMITER //
	CREATE TRIGGER beforeDATA BEFORE INSERT ON USUARI FOR EACH ROW
    BEGIN
		IF(YEAR(NOW()) - YEAR(NEW.DATA_NAIX) < 18) THEN
			CALL RAISE_ERROR_APPLICATION("Ets menor d'edat");
        END IF;
    END //
DELIMITER ;

INSERT INTO USUARI (ID, NOM, DATA_NAIX) VALUES (01, "Alberto", "2000/01/01");
INSERT INTO USUARI (ID, NOM, DATA_NAIX) VALUES (02, "Pepito", "2010/01/01");

SELECT * FROM USUARI;